services:
  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: docy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:

volumes:
  postgres_data:
